# Generated by Django 3.2.7 on 2022-04-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCafe', '0002_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liveImage',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
