# Generated by Django 4.0.4 on 2022-05-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCafe', '0005_contact_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='phone',
        ),
    ]
