# Generated by Django 4.0.4 on 2022-05-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCafe', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
